services:
  sms-service-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sms-service-api
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - sms-service-db
    networks:
      - sms-service-network

  sms-service-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sms-service-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DevPassword123!
      - MSSQL_PID=Express
    ports:
      - "3433:1433"
    networks:
      - sms-service-network
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P DevPassword123! -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sms-service-network:
    driver: bridge
